{% set version = "0.2.0" %}

package:
  name: xarray_mongodb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray_mongodb/xarray_mongodb-{{ version }}.tar.gz
  sha256: d0b5dc64774158ea39167f94627ffb5d6d1edb5972c45d4ed001902c0652ef51

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=3.6
    - setuptools
    - numpy >=1.15
    - pandas >=0.24
    - dask >=1.2
    - xarray >=0.13
    - pymongo >=3.7

test:
  imports:
    - xarray_mongodb
  requires:
    - pytest >=4
    - pytest-asyncio >=0.10

about:
  home: https://github.com/AmphoraInc/xarray_mongodb
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Store xarray objects in MongoDB

extra:
  recipe-maintainers:
    - crusaderky
    - gimperiale
