travis:
  secure:
    BINSTAR_TOKEN: gPkOtCF0zpif/5n2N/U6EHsrsueoz9nAvDCG1i6NLoqSPDS4aTbJ5DM6fSoktiu8ZyNGl7/DJfrfkr8ahkKstQtD0DstwwEvHPQ4xwKORqZGJt9yBWzWl4Xio9J1GzWxmDUEoaK/gzA3/0ZXv8IE6GNfbx6wV9RgqIHrmFmdnW5qTnWX0ZNV7MCUwEIjgiXkvx9rHjhAyaHcE6mgJnM3Wmn8j4UtqOItcNcFWtXBMyICUDzHqJN5CJHs5jB1Un7eYKohpZiZ9QC3Cd6QQRkiCiyEB9QDBgzKHkgTJUXqQqxiBHpO5xerwcFydiH+2DKMwGl4iiu/8p9bIlLt8jxGMqkhvKzlO0g1DujMDOeygN9PMow76XwOd3JB56E1/hyTZLjj4fmQVZX49gWTKFU0UsdlECfpUqkhgJE/KHHA4D1lTWtg4sYCNZHtVNOTM7yavGagxrXdylDusYLufDQZZTLwu0yQM7nuTUTJWt2uqJP60WRcUqS9bMZgvdqwrlx4ym9WZnAdoke5F8suH4HhOBwC/HS5Ag35bNCfy1Cyoh6bI5k2O/kiH9RNLWCG8PBAfftNH+mCe+pQma8MSu+uLiif3oUkqPkB1qoW5pDGQ/h77J6m0DQViMocvXyhBqc2Xdfauk8TJZrO+OIdeiUtMcPGbhEfmhywSC2l5qObdL0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
